package neural

import("context";"errors";"math";"sync";"time")
type Edge struct{From,To int;Weight float64;Name string}
type Layer struct{Activation string;DropoutRate float64}
type Config struct{Layers []Layer;Optimizer string;Regularization float64;GradientClip float64;Heads int;BatchCache int}
type NetworkStats struct{LearningSteps uint64;LastUpdate time.Time;LastGradient float64;Activations uint64}
type Network struct{mu sync.RWMutex;size int;edges map[int][]Edge;bias []float64;learningRate float64;config Config;adamM []float64;adamV []float64;stats NetworkStats;cache map[string][]float64}
func New(size int,learningRate float64)(*Network,error){if size<1{return nil,errors.New("network size must be positive")};if learningRate<1e-6||learningRate>0.1||math.IsNaN(learningRate)||math.IsInf(learningRate,0){return nil,errors.New("learning rate must be finite and in [1e-6,0.1]")};return &Network{size:size,edges:make(map[int][]Edge),bias:make([]float64,size),learningRate:learningRate,config:Config{Layers:[]Layer{{Activation:"tanh"}},Optimizer:"adam",Regularization:1e-6,GradientClip:1.0,Heads:1,BatchCache:128},adamM:make([]float64,size),adamV:make([]float64,size),cache:make(map[string][]float64)},nil}
func(n *Network)AddEdge(from,to int,weight float64)error{n.mu.Lock();defer n.mu.Unlock();if from<0||from>=n.size||to<0||to>=n.size{return errors.New("edge index out of range")};if from==to{return errors.New("self-cycle not allowed")};if math.IsNaN(weight)||math.IsInf(weight,0){return errors.New("invalid edge weight")};if n.pathExistsLocked(to,from){return errors.New("edge would create cycle")};for i,e:=range n.edges[from]{if e.To==to{n.edges[from][i].Weight=weight;return nil}};n.edges[from]=append(n.edges[from],Edge{From:from,To:to,Weight:weight,Name:"edge-"+time.Now().UTC().Format("150405.000000000")});return nil}
func(n *Network)pathExistsLocked(from,to int)bool{seen:=map[int]bool{};var dfs func(int)bool;dfs=func(v int)bool{if v==to{return true};if seen[v]{return false};seen[v]=true;for _,e:=range n.edges[v]{if dfs(e.To){return true}};return false};return dfs(from)}
func(n *Network)RemoveEdge(from,to int)error{n.mu.Lock();defer n.mu.Unlock();if from<0||from>=n.size||to<0||to>=n.size{return errors.New("edge index out of range")};edges:=n.edges[from];for i,e:=range edges{if e.To==to{copy(edges[i:],edges[i+1:]);n.edges[from]=edges[:len(edges)-1];return nil}};return errors.New("edge not found")}
func(n *Network)Activate(inputs []float64)([]float64,error){if len(inputs)==0{return nil,errors.New("empty input")};if len(inputs)%n.size!=0{return nil,errors.New("input size must equal network size or an exact batch multiple")};n.mu.RLock();bias:=append([]float64(nil),n.bias...);n.mu.RUnlock();out:=make([]float64,len(inputs));for off:=0;off<len(inputs);off+=n.size{for i:=0;i<n.size;i++{v:=inputs[off+i];if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("input contains non-finite value")};out[off+i]=activateValue(v+bias[i],n.config.Layers[0].Activation)}};n.mu.Lock();n.stats.Activations+=uint64(len(inputs)/n.size);n.mu.Unlock();return out,nil}
func activateValue(v,a string)float64{switch a{case "relu":if v>0{return v};return 0;case "sigmoid":return 1/(1+math.Exp(-v));case "linear":return v;default:return math.Tanh(v)}}
func(n *Network)Forward(ctx context.Context,inputs []float64)([]float64,error){if ctx==nil{return nil,errors.New("context is nil")};if len(inputs)!=n.size{return nil,errors.New("input size mismatch")};for _,v:=range inputs{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("input contains non-finite value")}};n.mu.RLock();state:=append([]float64(nil),inputs...);bias:=append([]float64(nil),n.bias...);edges:=make(map[int][]Edge,len(n.edges));for k,v:=range n.edges{edges[k]=append([]Edge(nil),v...)};cfg:=n.config;n.mu.RUnlock();for pass:=0;pass<len(cfg.Layers);pass++{select{case<-ctx.Done():return nil,ctx.Err();default:};next:=append([]float64(nil),bias...);for i,v:=range state{next[i]+=v};for from,es:=range edges{for _,e:=range es{next[e.To]+=state[from]*e.Weight}};for i:=range next{next[i]=activateValue(next[i],cfg.Layers[pass].Activation);if cfg.Layers[pass].DropoutRate>0{next[i]*=(1-cfg.Layers[pass].DropoutRate)}};state=next};n.mu.Lock();key:=cacheKey(inputs);n.cache[key]=append([]float64(nil),state...);if len(n.cache)>cfg.BatchCache{for k:=range n.cache{delete(n.cache,k);break}};n.mu.Unlock();return state,nil}
func cacheKey(v []float64)string{h:=uint64(1469598103934665603);for _,x:=range v{u:=math.Float64bits(x);h^=u;h*=1099511628211};return string([]byte{byte(h),byte(h>>8),byte(h>>16),byte(h>>24),byte(h>>32),byte(h>>40),byte(h>>48),byte(h>>56)})}
func(n *Network)Learn(inputs,target []float64)error{if len(inputs)!=n.size||len(target)!=n.size{return errors.New("training vector size mismatch")};for _,v:=range append(append([]float64{},inputs...),target...){if math.IsNaN(v)||math.IsInf(v,0){return errors.New("training data contains non-finite value")}};n.mu.Lock();defer n.mu.Unlock();pred:=make([]float64,n.size);for i:=range pred{pred[i]=math.Tanh(inputs[i]+n.bias[i])};clip:=n.config.GradientClip;if clip<=0{clip=1};sumAbs:=0.0;for i:=range pred{grad:=(pred[i]-target[i])*(1-pred[i]*pred[i])+n.config.Regularization*n.bias[i];if grad>clip{grad=clip};if grad< -clip{grad=-clip};switch n.config.Optimizer{case "sgd":n.bias[i]-=n.learningRate*grad;case "rmsprop":n.adamV[i]=.9*n.adamV[i]+.1*grad*grad;n.bias[i]-=n.learningRate*grad/(math.Sqrt(n.adamV[i])+1e-8);default:t:=float64(n.stats.LearningSteps+1);n.adamM[i]=.9*n.adamM[i]+.1*grad;n.adamV[i]=.999*n.adamV[i]+.001*grad*grad;mh:=n.adamM[i]/(1-math.Pow(.9,t));vh:=n.adamV[i]/(1-math.Pow(.999,t));n.bias[i]-=n.learningRate*mh/(math.Sqrt(vh)+1e-8)};sumAbs+=math.Abs(grad)};n.stats.LearningSteps++;n.stats.LastUpdate=time.Now().UTC();n.stats.LastGradient=sumAbs/float64(n.size);return nil}
func(n *Network)Normalize(values []float64)([]float64,error){if len(values)==0{return nil,errors.New("empty vector")};mean:=0.0;for _,v:=range values{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("invalid vector")};mean+=v};mean/=float64(len(values));variance:=0.0;for _,v:=range values{d:=v-mean;variance+=d*d};std:=math.Sqrt(variance/float64(len(values))+1e-12);out:=make([]float64,len(values));for i,v:=range values{out[i]=(v-mean)/std};return out,nil}
func(n *Network)Attention(query,keys,values []float64)([]float64,error){if len(query)==0||len(keys)==0||len(keys)!=len(values){return nil,errors.New("attention requires non-empty query, equal non-zero keys and values")};all:=append(append(append([]float64{},query...),keys...),values...);for _,v:=range all{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("attention input contains non-finite value")}};n.mu.RLock();heads:=n.config.Heads;if heads<1{heads=1};n.mu.RUnlock();scores:=make([]float64,len(keys));maxScore:=-math.MaxFloat64;scale:=math.Sqrt(float64(len(query)));for i,k:=range keys{q:=query[i%len(query)];if heads>1{q*=1+float64(i%heads)/float64(heads)};scores[i]=q*k/scale;if scores[i]>maxScore{maxScore=scores[i]}};sum:=0.0;for i:=range scores{scores[i]=math.Exp(scores[i]-maxScore);sum+=scores[i]};if math.IsNaN(sum)||math.IsInf(sum,0)||sum<=0{return nil,errors.New("attention normalization failed")};out:=make([]float64,len(values));for i,v:=range values{out[i]=v*scores[i]/sum};return out,nil}
func(n *Network)Backprop(inputs,target []float64)([]float64,error){if len(inputs)!=len(target)||len(inputs)==0{return nil,errors.New("backprop vectors must match")};grad:=make([]float64,len(inputs));clip:=1.0;n.mu.RLock();if n.config.GradientClip>0{clip=n.config.GradientClip};n.mu.RUnlock();sum:=0.0;for i:=range inputs{if math.IsNaN(inputs[i])||math.IsNaN(target[i])||math.IsInf(inputs[i],0)||math.IsInf(target[i],0){return nil,errors.New("backprop data contains non-finite value")};pred:=math.Tanh(inputs[i]);grad[i]=(pred-target[i])*(1-pred*pred);if grad[i]>clip{grad[i]=clip};if grad[i] < -clip{grad[i]=-clip};sum+=math.Abs(grad[i])};if math.IsNaN(sum)||math.IsInf(sum,0){return nil,errors.New("invalid gradient")};return grad,nil}
func(n *Network)Health()map[string]any{n.mu.RLock();defer n.mu.RUnlock();edges:=0;for _,e:=range n.edges{edges+=len(e)};density:=0.0;if n.size>1{density=float64(edges)/float64(n.size*(n.size-1))};return map[string]any{"status":"ready","size":n.size,"edges":edges,"density":density,"learning_steps":n.stats.LearningSteps,"last_update":n.stats.LastUpdate,"last_gradient":n.stats.LastGradient,"activations":n.stats.Activations,"optimizer":n.config.Optimizer,"heads":n.config.Heads}}
