package neural

import("context";"errors";"math";"sync")
type Edge struct{From,To int;Weight float64}
type Network struct{mu sync.RWMutex;size int;edges map[int][]Edge;bias []float64;learningRate float64;steps uint64}
func New(size int,learningRate float64)(*Network,error){if size<1{return nil,errors.New("network size must be positive")};if learningRate<=0||learningRate>1||math.IsNaN(learningRate)||math.IsInf(learningRate,0){return nil,errors.New("learning rate must be finite and in (0,1]")};return &Network{size:size,edges:make(map[int][]Edge),bias:make([]float64,size),learningRate:learningRate},nil}
func(n *Network)AddEdge(from,to int,weight float64)error{n.mu.Lock();defer n.mu.Unlock();if from<0||from>=n.size||to<0||to>=n.size{return errors.New("edge index out of range")};if math.IsNaN(weight)||math.IsInf(weight,0){return errors.New("invalid edge weight")};for i,e:=range n.edges[from]{if e.To==to{n.edges[from][i].Weight=weight;return nil}};n.edges[from]=append(n.edges[from],Edge{from,to,weight});return nil}
func(n *Network)RemoveEdge(from,to int)error{n.mu.Lock();defer n.mu.Unlock();if from<0||from>=n.size||to<0||to>=n.size{return errors.New("edge index out of range")};edges:=n.edges[from];for i,e:=range edges{if e.To==to{copy(edges[i:],edges[i+1:]);n.edges[from]=edges[:len(edges)-1];return nil}};return errors.New("edge not found")}
func(n *Network)Activate(inputs []float64)([]float64,error){if len(inputs)!=n.size{return nil,errors.New("input size mismatch")};for _,v:=range inputs{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("input contains non-finite value")}};n.mu.RLock();defer n.mu.RUnlock();out:=make([]float64,n.size);for i,v:=range inputs{out[i]=math.Tanh(v+n.bias[i])};return out,nil}
func(n *Network)Forward(ctx context.Context,inputs []float64)([]float64,error){if ctx==nil{return nil,errors.New("context is nil")};if len(inputs)!=n.size{return nil,errors.New("input size mismatch")};for _,v:=range inputs{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("input contains non-finite value")}};n.mu.RLock();state:=append([]float64(nil),inputs...);bias:=append([]float64(nil),n.bias...);edges:=make(map[int][]Edge,len(n.edges));for k,v:=range n.edges{edges[k]=append([]Edge(nil),v...)};n.mu.RUnlock();for pass:=0;pass<n.size;pass++{select{case<-ctx.Done():return nil,ctx.Err();default:};next:=append([]float64(nil),bias...);for i,v:=range state{next[i]+=v};for from,es:=range edges{for _,e:=range es{next[e.To]+=state[from]*e.Weight}};for i:=range next{next[i]=math.Tanh(next[i])};state=next};return state,nil}
func(n *Network)Learn(inputs,target []float64)error{if len(inputs)!=n.size||len(target)!=n.size{return errors.New("training vector size mismatch")};for _,v:=range append(append([]float64{},inputs...),target...){if math.IsNaN(v)||math.IsInf(v,0){return errors.New("training data contains non-finite value")}};n.mu.Lock();defer n.mu.Unlock();pred:=make([]float64,n.size);for i:=range pred{pred[i]=math.Tanh(inputs[i]+n.bias[i])};for i:=range pred{err:=target[i]-pred[i];n.bias[i]+=n.learningRate*err*(1-pred[i]*pred[i])};n.steps++;return nil}
func(n *Network)Normalize(values []float64)([]float64,error){if len(values)==0{return nil,errors.New("empty vector")};mean:=0.0;for _,v:=range values{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("invalid vector")};mean+=v};mean/=float64(len(values));variance:=0.0;for _,v:=range values{d:=v-mean;variance+=d*d};std:=math.Sqrt(variance/float64(len(values))+1e-12);out:=make([]float64,len(values));for i,v:=range values{out[i]=(v-mean)/std};return out,nil}
func(n *Network)Attention(query,keys,values []float64)([]float64,error){if len(query)==0||len(keys)==0||len(keys)!=len(values){return nil,errors.New("attention requires non-empty query, equal non-zero keys and values")};all:=make([]float64,0,len(query)+len(keys)+len(values));all=append(all,query...);all=append(all,keys...);all=append(all,values...);for _,v:=range all{if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("attention input contains non-finite value")}};scores:=make([]float64,len(keys));maxScore:=-math.MaxFloat64;scale:=math.Sqrt(float64(len(query)));for i,k:=range keys{if len(query)==1{scores[i]=query[0]*k}else{scores[i]=k*query[i%len(query)]};scores[i]/=scale;if scores[i]>maxScore{maxScore=scores[i]}};sum:=0.0;for i:=range scores{scores[i]=math.Exp(scores[i]-maxScore);sum+=scores[i]};if math.IsNaN(sum)||math.IsInf(sum,0)||sum<=0{return nil,errors.New("attention normalization failed")};out:=make([]float64,len(values));for i,v:=range values{out[i]=v*scores[i]/sum};return out,nil}
func(n *Network)Backprop(inputs,target []float64)([]float64,error){if len(inputs)!=len(target)||len(inputs)==0{return nil,errors.New("backprop vectors must match")};for _,v:=range append(append([]float64{},inputs...),target...){if math.IsNaN(v)||math.IsInf(v,0){return nil,errors.New("backprop data contains non-finite value")}};grad:=make([]float64,len(inputs));for i:=range inputs{pred:=math.Tanh(inputs[i]);grad[i]=(pred-target[i])*(1-pred*pred)};return grad,nil}
func(n *Network)Health()map[string]any{n.mu.RLock();defer n.mu.RUnlock();edges:=0;for _,e:=range n.edges{edges+=len(e)};return map[string]any{"status":"ready","size":n.size,"edges":edges,"learning_steps":n.steps,"learning_rate":n.learningRate}}
