package prefrontal

import("errors";"math";"sort";"sync";"time")
type Candidate struct{ID string;Score float64;Cost float64;Risk float64;Utility float64}
type Decision struct{ID string;Score float64;Reason string;Committed bool;At time.Time}
type Cortex struct{mu sync.RWMutex;decisions []Decision;threshold float64;capacity int}
func New(threshold float64,capacity int)(*Cortex,error){if threshold<0||threshold>1||math.IsNaN(threshold)||math.IsInf(threshold,0){return nil,errors.New("threshold must be finite and between 0 and 1")};if capacity<1{return nil,errors.New("capacity must be positive")};return &Cortex{threshold:threshold,capacity:capacity},nil}
func valid(v Candidate)error{if v.ID==""{return errors.New("candidate id is required")};for _,x:=range []float64{v.Cost,v.Risk,v.Utility,v.Score}{if math.IsNaN(x)||math.IsInf(x,0){return errors.New("candidate contains non-finite value")}};if v.Cost<0||v.Risk<0{return errors.New("cost and risk cannot be negative")};if v.Risk>1{return errors.New("risk must be <= 1")};return nil}
func score(v Candidate)float64{return v.Utility-v.Cost-v.Risk}
func(c *Cortex)Evaluate(candidates []Candidate)(Candidate,error){best:=Candidate{};bestScore:=-math.MaxFloat64;found:=false;for _,v:=range candidates{if err:=valid(v);err!=nil{continue};s:=score(v);if s>bestScore{best,bestScore,found=v,s,true}};if !found{return Candidate{},errors.New("no valid candidates")};if bestScore<c.threshold{return Candidate{},errors.New("no candidate exceeds decision threshold")};return best,nil}
func(c *Cortex)Plan(candidates []Candidate)([]Candidate,error){if len(candidates)==0{return nil,errors.New("no candidates")};out:=make([]Candidate,0,len(candidates));for _,v:=range candidates{if valid(v)==nil{out=append(out,v)}};if len(out)==0{return nil,errors.New("no valid candidates")};sort.SliceStable(out,func(i,j int)bool{si,sj:=score(out[i]),score(out[j]);if si==sj{return out[i].ID<out[j].ID};return si>sj});if len(out)>c.capacity{out=out[:c.capacity]};return out,nil}
func(c *Cortex)Prioritize(candidates []Candidate)([]Candidate,error){return c.Plan(candidates)}
func(c *Cortex)Inhibit(candidate Candidate)bool{return valid(candidate)!=nil||candidate.Risk>candidate.Utility||candidate.Risk>=1}
func(c *Cortex)Select(candidates []Candidate)(Candidate,error){planned,err:=c.Plan(candidates);if err!=nil{return Candidate{},err};for _,v:=range planned{if !c.Inhibit(v)&&score(v)>=c.threshold{return v,nil}};return Candidate{},errors.New("all candidates inhibited or below threshold")}
func(c *Cortex)ValidateAction(candidate Candidate)error{if err:=valid(candidate);err!=nil{return err};if c.Inhibit(candidate){return errors.New("action inhibited by risk policy")};if score(candidate)<c.threshold{return errors.New("action below decision threshold")};return nil}
func(c *Cortex)Commit(candidate Candidate,reason string)(Decision,error){if err:=c.ValidateAction(candidate);err!=nil{return Decision{},err};if reason==""{return Decision{},errors.New("decision reason is required")};d:=Decision{ID:candidate.ID,Score:score(candidate),Reason:reason,Committed:true,At:time.Now().UTC()};c.mu.Lock();defer c.mu.Unlock();c.decisions=append(c.decisions,d);if len(c.decisions)>c.capacity{c.decisions=c.decisions[len(c.decisions)-c.capacity:]};return d,nil}
func(c *Cortex)Recall(limit int)[]Decision{c.mu.RLock();defer c.mu.RUnlock();if limit<=0||limit>len(c.decisions){limit=len(c.decisions)};out:=make([]Decision,limit);copy(out,c.decisions[len(c.decisions)-limit:]);return out}
func(c *Cortex)Health()map[string]any{c.mu.RLock();defer c.mu.RUnlock();return map[string]any{"status":"ready","threshold":c.threshold,"capacity":c.capacity,"decisions":len(c.decisions)}}
