package mesh

import("bytes";"context";"encoding/json";"errors";"fmt";"net/http";"strings";"time";"github.com/divibisoul/Orquestrador-/protocol")

type Adapter struct{BaseURL string;Nucleus string;Client *http.Client;ContractVersion string}
func New(baseURL string) (*Adapter,error){baseURL=strings.TrimRight(strings.TrimSpace(baseURL),"/");if baseURL==""{return nil,errors.New("mesh base URL is required")};return &Adapter{BaseURL:baseURL,Nucleus:"N07",Client:&http.Client{Timeout:15*time.Second},ContractVersion:"1.2"},nil}
func(a *Adapter)Envelope(operation,correlation,target string,payload map[string]any)(protocol.MeshEnvelope,error){m:=protocol.MeshEnvelope{ContractVersion:a.ContractVersion,Operation:operation,Payload:payload,CorrelationID:correlation,Source:a.Nucleus,Target:target,Metadata:map[string]string{"nucleus":"N07"}};return m,m.Validate()}
func(a *Adapter)Send(ctx context.Context,targetURL string,m protocol.MeshEnvelope)(map[string]any,error){if ctx==nil{return nil,errors.New("context is nil")};if err:=m.Validate();err!=nil{return nil,err};b,_:=protocol.EncodeMesh(m);req,err:=http.NewRequestWithContext(ctx,http.MethodPost,strings.TrimRight(targetURL,"/"),bytes.NewReader(b));if err!=nil{return nil,err};req.Header.Set("Content-Type","application/json");req.Header.Set("X-Soul-Contract-Version",a.ContractVersion);resp,err:=a.Client.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();if resp.StatusCode<200||resp.StatusCode>=300{return nil,fmt.Errorf("mesh target returned HTTP %d",resp.StatusCode)};var out map[string]any;if err:=json.NewDecoder(resp.Body).Decode(&out);err!=nil{return nil,err};return out,nil}
func(a *Adapter)Health(ctx context.Context)(map[string]any,error){req,err:=http.NewRequestWithContext(ctx,http.MethodGet,a.BaseURL+"/health",nil);if err!=nil{return nil,err};resp,err:=a.Client.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();var out map[string]any;if err:=json.NewDecoder(resp.Body).Decode(&out);err!=nil{return nil,err};if resp.StatusCode<200||resp.StatusCode>=300{return out,fmt.Errorf("mesh health returned HTTP %d",resp.StatusCode)};return out,nil}
func(a *Adapter)Register(ctx context.Context,registryURL string,capabilities []string)(map[string]any,error){if registryURL==""{return nil,errors.New("registry URL is required")};body:=map[string]any{"nucleus":a.Nucleus,"contractVersion":a.ContractVersion,"capabilities":capabilities,"transports":[]string{"LOOPBACK_HTTP","HTTP"}};b,_:=json.Marshal(body);req,err:=http.NewRequestWithContext(ctx,http.MethodPost,strings.TrimRight(registryURL,"/")+"/registry/nodes",bytes.NewReader(b));if err!=nil{return nil,err};req.Header.Set("Content-Type","application/json");resp,err:=a.Client.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();var out map[string]any;_ = json.NewDecoder(resp.Body).Decode(&out);if resp.StatusCode<200||resp.StatusCode>=300{return out,fmt.Errorf("mesh registry returned HTTP %d",resp.StatusCode)};return out,nil}
