package mesh

import("bytes";"context";"encoding/json";"errors";"io";"net/http";"strings";"time";"github.com/divibisoul/Orquestrador-/orchestrator";"github.com/divibisoul/Orquestrador-/protocol")

type FederatedGateway struct{base *HTTPGateway;peers *PeerClient;engine *orchestrator.Engine}
func NewFederatedHTTPGateway(engine *orchestrator.Engine)*FederatedGateway{return &FederatedGateway{base:NewHTTPGateway(engine),peers:mustPeerClient(),engine:engine}}
func mustPeerClient()*PeerClient{p,err:=NewPeerClient(nil);if err!=nil{return &PeerClient{}};return p}
func(g *FederatedGateway)ServeHTTP(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{g.base.Handler(w,r);return};if g.engine==nil{g.base.Handler(w,r);return};body,err:=ioReadLimited(r.Body,1<<20);if err!=nil{writeMeshJSON(w,http.StatusBadRequest,map[string]any{"error":err.Error()});return};r.Body=ioNopCloser(bytes.NewReader(body));var wire canonicalWireEnvelope;if err:=json.Unmarshal(body,&wire);err!=nil{g.base.Handler(w,r);return};capability:=canonicalCapability(wire);if capability==""{g.base.Handler(w,r);return};if isLocalOperation(g.engine,capability){r.Body=ioNopCloser(bytes.NewReader(body));g.base.Handler(w,r);return};envelope:=normalizedMeshEnvelope(wire);if err:=envelope.Validate();err!=nil{g.base.Handler(w,r);return};if err:=g.base.authenticateWire(wire,r,envelope);err!=nil{g.base.Handler(w,r);return};if envelope.Target!=protocol.N07&&envelope.Target!="BROADCAST"{g.base.respond(w,http.StatusBadRequest,envelope,"ERROR",map[string]any{"error":"target is not N07"});return};switch strings.ToLower(capability){case "mesh.ping":g.base.respond(w,http.StatusOK,envelope,"TASK_RESULT",map[string]any{"ok":true,"nucleus":protocol.N07,"contractVersion":protocol.SoulMeshContractVersion});return;case "mesh.describe","mesh.discovery","mesh.capabilities","mesh.fusion.describe":g.handleDescribe(w,envelope);return;case "mesh.fusion.execute","fusion.execute":g.handleComposition(w,r,envelope);return};payload:=envelope.NestedPayload();if payload==nil{payload=map[string]any{}};peer,descErr:=g.selectPeer(r.Context(),capability);if descErr!=nil{g.base.respond(w,http.StatusServiceUnavailable,envelope,"ERROR",map[string]any{"error":"no federated peer capability available","capability":capability,"details":descErr.Error()});return};result,err:=g.peers.CallWithCorrelation(r.Context(),peer,capability,payload,envelope.CorrelationID);if err!=nil{g.base.respond(w,http.StatusBadGateway,envelope,"ERROR",map[string]any{"error":"delegated capability failed","peer":peer,"capability":capability,"details":err.Error()});return};g.base.respond(w,http.StatusOK,envelope,"TASK_RESULT",map[string]any{"delegated":true,"peer":peer,"capability":capability,"result":result["payload"],"completedAt":time.Now().UnixMilli()})}
func(g *FederatedGateway)handleDescribe(w http.ResponseWriter,in protocol.MeshEnvelope){g.base.respond(w,http.StatusOK,in,"TASK_RESULT",map[string]any{"nucleus":protocol.N07,"contractVersion":protocol.SoulMeshContractVersion,"operations":g.engine.Operations(),"capabilityOwnership":VerifiedN01N06Catalog(),"peers":g.peers.ConfiguredPeers(),"transports":[]string{"IN_PROCESS","LOOPBACK_HTTP","HTTP","REALTIME"}})}
func isLocalOperation(engine *orchestrator.Engine,capability string)bool{for _,operation:=range engine.Operations(){name:=operation;if i:=strings.LastIndex(operation,"@");i>0{name=operation[:i]};if name==capability{return true}};return false}
func(g *FederatedGateway)selectPeer(ctx context.Context,capability string)(string,error){if owner:=KnownFusionOwner(capability);owner!=""{for _,peer:=range g.peers.ConfiguredPeers(){if peer.Nucleus==owner&&!(peer.Circuit==CircuitOpen&&time.Now().Before(peer.RetryAfter)){return owner,nil}}};configured:=g.peers.ConfiguredPeers();var lastErr error;for _,peer:=range configured{if peer.Circuit==CircuitOpen&&time.Now().Before(peer.RetryAfter){continue};desc,err:=g.peers.Discover(ctx,peer.Nucleus);if err!=nil{lastErr=err;continue};if capabilityInDescription(desc,capability){return peer.Nucleus,nil}};if lastErr!=nil{return "",lastErr};return "",errors.New("capability not discovered on configured peers: "+capability)}
func capabilityInDescription(desc map[string]any,target string)bool{target=strings.TrimSpace(target);for _,key:=range []string{"capabilities","operations","executableCapabilities"}{items,ok:=desc[key].([]any);if !ok{continue};for _,raw:=range items{if value,ok:=raw.(string);ok&&strings.TrimSpace(strings.SplitN(value,"@",2)[0])==target{return true}}};return false}
func(g *FederatedGateway)handleComposition(w http.ResponseWriter,r *http.Request,in protocol.MeshEnvelope){payload:=in.NestedPayload();if payload==nil{payload=map[string]any{}};raw,ok:=payload["steps"].([]any);if !ok||len(raw)==0{g.base.respond(w,http.StatusBadRequest,in,"ERROR",map[string]any{"error":"fusion.execute requires payload.steps"});return};results:=make([]map[string]any,0,len(raw));current:=map[string]any{};for k,v:=range payload{if k!="steps"{current[k]=v}};for i,item:=range raw{step,ok:=item.(map[string]any);if !ok{g.base.respond(w,http.StatusBadRequest,in,"ERROR",map[string]any{"error":"fusion step must be object"});return};capability,_:=step["capability"].(string);capability=strings.TrimSpace(capability);if capability==""{g.base.respond(w,http.StatusBadRequest,in,"ERROR",map[string]any{"error":"fusion step capability is required"});return};stepPayload,_:=step["payload"].(map[string]any);if stepPayload==nil{stepPayload=map[string]any{"input":current}};started:=time.Now();peer,err:=g.selectPeer(r.Context(),capability);entry:=map[string]any{"index":i,"capability":capability,"duration_ms":0};if err==nil{entry["owner"]=peer;var result map[string]any;result,err=g.peers.CallWithCorrelation(r.Context(),peer,capability,stepPayload,in.CorrelationID);if err==nil{entry["status"]="ok";entry["result"]=result["payload"];current=map[string]any{"previous":result["payload"],"capability":capability}}};entry["duration_ms"]=time.Since(started).Milliseconds();if err!=nil{entry["status"]="error";entry["error"]=err.Error();results=append(results,entry);required,_:=step["required"].(bool);if required{g.base.respond(w,http.StatusBadGateway,in,"ERROR",map[string]any{"execution":"federated-composition","steps":results});return};continue};results=append(results,entry)};g.base.respond(w,http.StatusOK,in,"TASK_RESULT",map[string]any{"execution":"federated-composition","correlationId":in.CorrelationID,"steps":results,"finalInput":current})}
func ioReadLimited(r io.Reader,max int64)([]byte,error){if r==nil{return nil,errors.New("request body is nil")};data,err:=io.ReadAll(io.LimitReader(r,max+1));if err!=nil{return nil,err};if int64(len(data))>max{return nil,errors.New("request body exceeds configured limit")};return data,nil}
func ioNopCloser(r io.Reader)io.ReadCloser{return io.NopCloser(r)}
