package mesh

import("bytes";"context";"encoding/json";"errors";"net/http";"os";"strings";"sync";"time";"github.com/divibisoul/Orquestrador-/protocol")
type PeerInfo struct{Nucleus string;URL string;Healthy bool;Latency time.Duration;LastError string}
type PeerClient struct{mu sync.RWMutex;peers map[string]PeerInfo;client *http.Client;secret string}
func NewPeerClient(client *http.Client)(*PeerClient,error){if client==nil{client=&http.Client{Timeout:15*time.Second}};peers:=map[string]PeerInfo{};for _,n:=range []string{protocol.N01,protocol.N02,protocol.N03,protocol.N04,protocol.N05,protocol.N06}{if u:=strings.TrimRight(strings.TrimSpace(os.Getenv("SOUL_MESH_"+n+"_URL")),"/");u!=""{peers[n]=PeerInfo{Nucleus:n,URL:u}}};return &PeerClient{peers:peers,client:client,secret:strings.TrimSpace(os.Getenv("SOUL_MESH_HMAC_SECRET"))},nil}
func(p *PeerClient)Discover(ctx context.Context,nucleus string)(map[string]any,error){return p.call(ctx,nucleus,"mesh.discovery",map[string]any{"from":protocol.N07})}
func(p *PeerClient)Call(ctx context.Context,nucleus,capability string,payload map[string]any)(map[string]any,error){if ctx==nil{return nil,errors.New("context is nil")};nucleus=strings.TrimSpace(nucleus);capability=strings.TrimSpace(capability);if nucleus==protocol.N07{return nil,errors.New("N07 cannot call itself through peer transport")};if capability==""{return nil,errors.New("capability is required")};return p.call(ctx,nucleus,capability,payload)}
func(p *PeerClient)call(ctx context.Context,nucleus,capability string,payload map[string]any)(map[string]any,error){if ctx==nil{return nil,errors.New("context is nil")};p.mu.RLock();peer,ok:=p.peers[nucleus];p.mu.RUnlock();if !ok{return nil,errors.New("peer not configured: "+nucleus)};correlation:=protocol.NewTraceID();env:=protocol.MeshEnvelope{Version:protocol.SoulMeshVersion,ContractVersion:protocol.SoulMeshContractVersion,MessageID:protocol.NewTraceID(),Source:protocol.N07,Target:nucleus,Timestamp:time.Now().UnixMilli(),Nonce:protocol.NewTraceID(),CorrelationID:correlation,Type:"CAPABILITY_REQUEST",Payload:map[string]any{"capability":capability,"payload":payload}};if p.secret==""{return nil,errors.New("SOUL_MESH_HMAC_SECRET is not configured")};if err:=protocol.SignHMAC(&env,p.secret);err!=nil{return nil,err};body,err:=protocol.EncodeMesh(env);if err!=nil{return nil,err};req,err:=http.NewRequestWithContext(ctx,http.MethodPost,peer.URL+"/api/soul-mesh",bytes.NewReader(body));if err!=nil{return nil,err};req.Header.Set("Content-Type","application/json");req.Header.Set("X-Soul-Contract-Version",protocol.SoulMeshContractVersion);started:=time.Now();resp,err:=p.client.Do(req);latency:=time.Since(started);if err!=nil{p.record(nucleus,false,latency,err.Error());return nil,err};defer resp.Body.Close();var result map[string]any;if err:=json.NewDecoder(resp.Body).Decode(&result);err!=nil{p.record(nucleus,false,latency,err.Error());return nil,err};if resp.StatusCode<200||resp.StatusCode>=300{err=errors.New("peer request failed: "+resp.Status);p.record(nucleus,false,latency,err.Error());return result,err};if result["correlationId"]!=correlation{err=errors.New("peer correlation mismatch");p.record(nucleus,false,latency,err.Error());return nil,err};p.record(nucleus,true,latency,"");return result,nil}
func(p *PeerClient)record(nucleus string,healthy bool,latency time.Duration,lastError string){p.mu.Lock();defer p.mu.Unlock();peer,ok:=p.peers[nucleus];if !ok{return};peer.Healthy=healthy;peer.Latency=latency;peer.LastError=lastError;p.peers[nucleus]=peer}
func(p *PeerClient)ConfiguredPeers()[]PeerInfo{p.mu.RLock();defer p.mu.RUnlock();out:=make([]PeerInfo,0,len(p.peers));for _,peer:=range p.peers{out=append(out,peer)};return out}
